#!/bin/sh

dir="ms";
pt="";
all_flag=0;
tools="`dirname $0`";
while [ $# -gt 0 ] ; do
		case $1 in
				-i | --img) dir="$2"; shift; shift;;
				-a | --all) all_flag=1; shift;;
				-t | --tgt | --target) pt="$2"; shift; shift;;
				--tools) tools="$2"; shift; shift;;
				*) shift;;
		esac;
done

if [ ! "$pt" ] ; then
	if [ "$MEMSTICK_ROOT" ] ; then
		pt="$MEMSTICK_ROOT";
	else
		case "`uname`" in
			CYGWIN*) pt="/cygdrive/e";;
			Darwin) d="`dirname $0`"; pt="`$d/osx_find_memstick`";;
			*) pt="/mnt/memstick";;
		esac
	fi;
fi;

${tools}/mntmem ${pt};
if [ "`uname`" = "Darwin" ] ; then
	if [ ! $all_flag -eq 1 ] ; then
		echo "cpymem: cp 'update' unsupported on os x"
	fi;
	cp -pHRv ${dir}/* $pt/ || exit 1;
else
	if [ $all_flag -eq 1 ] ; then
		cp -pHrv ${dir}/* $pt/
	else
		cp -pHrvu ${dir}/* $pt/
	fi;
fi;
${tools}/umntmem ${pt};
