//-*-c++-*-
#ifndef INCLUDED_Gamepad_h
#define INCLUDED_Gamepad_h

#define IS_GAMEPAD_SID(i) ((i) >= GamepadSrcID::gamepadXButtonSrcID && (i) <= GamepadSrcID::gamepadRightBumperSrcID)

class EventBase;

//Gamepad SourceIDs for events generated by gamepadEGID
namespace GamepadSrcID {
	//! holds source ID types for gamepad events
	enum GamepadSourceID_t {
		gamepadXButtonSrcID = 1000, //!< The x button
		gamepadYButtonSrcID, //!< The y button
		gamepadAButtonSrcID, //!< The a button
		gamepadBButtonSrcID, //!< The b button
		gamepadStartButtonSrcID, //!< The start button
		gamepadSelectButtonSrcID, //!< The select button
		gamepadLeftJoyXSrcID, //!< The left joystick
		gamepadLeftJoyYSrcID, //!< The left joystick
		gamepadRightJoyXSrcID, //!< The right joystick
		gamepadRightJoyYSrcID, //!< The right joystick
		gamepadDPadXSrcID, //!< The D-pad
		gamepadDPadYSrcID, //!< The D-pad
		gamepadLeftBumperSrcID, //!< Left bumper
		gamepadRightBumperSrcID //!< Right bumper
	};
}

#endif
