#!/bin/sh

cd "`dirname \"$0\"`/../mon"
if [ ! -r org/tekkotsu/mon/ControllerGUI.java ] ; then
	echo "Cannot access org/tekkotsu/mon/ControllerGUI.java"
	echo "Make sure this script is located at the root of the java package tree"
	echo "(i.e. Tekkotsu/tools/mon)"
	exit 1;
fi;

if [ ! -r org/tekkotsu/mon/ControllerGUI.class ] ; then
	echo "Cannot access Java executable."
	echo "Perhaps the tools need to be compiled.  Go to the Tekkotsu/tools"
	echo "directory and type 'make'"
	exit 1;
fi;

if [ -z "$1" ]; then
        echo "Usage:  `basename \"$0\"` hostname-or-ip-addr [-g]"
	echo Use \"localhost\" if Tekkotsu is running on this computer.
	exit 1
fi

if [ "`uname`" = "Darwin" ] ; then
	JAVAFLAGS="${JAVAFLAGS} -Xdock:name=ControllerGUI -Xdock:icon=images/ControllerIcon.png"
fi

echo "Launching, window will appear in a moment..."

# class libraries needed by SketchPanel3D and Gamepad interface
export CLASSPATH=".:./java3d/j3dcore.jar:./java3d/j3dutils.jar:./java3d/vecmath.jar:/usr/share/java/jinput.jar"

java ${JAVAFLAGS} -Xmx256M -cp "$CLASSPATH" org.tekkotsu.mon.ControllerGUI $* &
